### PR TITLE
docs: grammar and spelling

### PR DESCRIPTION
**Pull request by Charlotteis**
:v:

### CODE REVIEW

**Comment by christophwitzko** [comment]
Awesome :+1: :tada: 
Thank you! :relaxed:

**Comment by christophwitzko** [comment]
I just saw you committed this change as `fix`. Regarding the angular commit message conventions, this change should have the type `docs`. :wink:

**Comment by Charlotteis** [comment]
@christophwitzko woops! have updated, thanks :)

**Comment by christophwitzko** [comment]
:relaxed: :ok_hand:

**Comment by lycon2014** [comment]
I'm very curious

**Pull request merged**
